# main text of home
name: Zhuoxinran
title: Zhuoxinran Li
bio: Frontend Developer that plays drums on weekends

# twitter summary info
description: My personal page, Zhuoxinran Li

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/juanjuan.gif

# your site color theme, true for dark theme, 
# false to light theme, auto to switch with system.
dark-theme: false

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: https://raw.githubusercontent.com/sergiokopplin/koppl.in/gh-pages/assets/images/resume-sergio-kopplin.pdf

url: https://zoezxrli.github.io/

permalink: /:title/

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: zoezxrli # enter this from your disqus account
  categories: [blog, project, notas] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: xxx
# twitter: xxx
instagram: yigezhuoe/
linkedin: zhuoxinranli
github: zoezxrli
email: zhuoxinran.li@mail.utoronto.ca
# linktree: xxx
# youtube: xxx

authors:
  johndoe:
    name: John Doe
    bio: A Man who travels the world eating noodles
    external-image: false
    picture: assets/images/juanjuan.gif
    twitter: johndoe
  jamesfoster:
    name: James Foster
    bio: A Man who develops software with coffee
    external-image: false
    picture: assets/images/juanjuan.gif
    twitter: jamesfoster

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you do/don't need pagination, toggle 'enabled' between true/false below
pagination:
  enabled: false
  sort_reverse: true # display recent posts first
  title: ":title" # Changing this will mess up the header display logic
  per_page: 5
  permalink: "/:num/" # pagination link that will be appended



projects: true
about: true
blog: true

# if you don't need "about" or "blog", comment them out below
notas: false
setup: false

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
# post-advance-links: [blog,notas]

# show author block at the end of a post ?
show-author: false

# do you want some animations?
animation: true

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-paginate-v2
  - jekyll-redirect-from

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
